export default [
	{ value: 'eq', label: 'Equals' },
	{ value: 'neq', label: "Doesn't equal" },
	{ value: 'lt', label: 'Less than' },
	{ value: 'gt', label: 'Greater than' },
	{ value: 'lte', label: 'Less than or equal to' },
	{ value: 'gte', label: 'Greater than or equal to' },
	{ value: 'in', label: 'Is one of' },
	{ value: 'nin', label: 'Is not one of' },
	{ value: 'null', label: 'Is null' },
	{ value: 'nnull', label: "Isn't null" },
	{ value: 'contains', label: 'Contains' },
	{ value: 'ncontains', label: "Doesn't contain" },
	{ value: 'icontains', label: 'Contains (insensitive)' },
	{ value: 'starts_with', label: 'Starts with' },
	{ value: 'nstarts_with', label: "Doesn't start with" },
	{ value: 'ends_with', label: 'Ends with' },
	{ value: 'nends_with', label: "Doesn't end with" },
	{ value: 'between', label: 'Is between' },
	{ value: 'nbetween', label: "Isn't between" },
	{ value: 'empty', label: 'Is empty' },
	{ value: 'nempty', label: "Isn't empty" },
	{ value: 'all', label: 'Contains these keys' },
	{ value: 'has', label: 'Contains some of these keys' },
	{ value: 'intersects', label: 'Intersects' },
	{ value: 'nintersects', label: "Doesn't intersect" },
	{ value: 'intersects_bbox', label: 'Intersects bounding box' },
	{ value: 'nintersects_bbox', label: "Doesn't intersect bounding box" },
]
